### ISSUE TITLE
VNC output garbled

### ISSUE THREAD

**Issue by sandervankasteel** [tom300z/backblaze-personal-wine#4]
Hi! I've just come across your Docker image and I am currently trying it out, but as you can see from the screenshot, the VNC / Wine output is pretty much garbled. 

I've tried it with TigerVNC as well as with vinagre. Any tips on how to resolve this ?

![image](https://user-images.githubusercontent.com/17492906/137534309-7974fc76-2115-46d4-956c-da524ce25bed.png)

**Comment by tom300z** [comment]
README: When you only see a black screen once you are connected press alt-tab to activate the installer window. The installer might look a bit weird (all white) at the very beginning. Just enter your backblaze account email into the white box and hit enter, then the you should see the rest of the ui. Enter your password and hit "Install", the installer will start scanning your drive.
