### ISSUE TITLE
ALT+TAB not working from RealVNC Viewer on Mac

### ISSUE THREAD

**Issue by minovap** [tom300z/backblaze-personal-wine#7]
I am tunnin the container and can connect to it, but I can't get past the black screen. I have tried configuring VNC Viewer to send special keys, tried full screen, tried mapping LeftOption key to ALT_L, to ALT_R etc - but nothing makes the VNC screen go from black to showing the Backblaze installer.

I am suspecting the problem is due to me trying this on a Mac, or that the Backblaze installer is not running. Here is the log from Docker container which has some errors/warnings.

Do you have any suggestions on what I can try next?

Thanks

````

Starting the virtual display & vnc server

cp: can't stat '/wine//drive_c/Program Files/Backblaze/bzbui.exe.aside': No such file or directory

Backblaze not installed

Initializing the wine prefix


 --- x11vnc loop: 1 ---


_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

How are you gentlemen? All your base are belong to us. (Openbox received signal 11)

 --- x11vnc loop: waiting for: 43


Xlib:  extension "DPMS" missing on display ":0".


The VNC desktop is:      b2a94b2039b3:0


0

Directory '//.local/share/mime/packages' does not exist!

Directory '//.local/share/mime/packages' does not exist!

wine: configuration in '/wine' has been updated.

unlink: can't remove file '/wine//dosdevices/z:': No such file or directory

ln: /wine//dosdevices/d:/data: Permission denied

Setting the wine computer name

The operation completed successfully

The operation completed successfully

The operation completed successfully

Downloading the Backblaze personal installer...

Connecting to www.backblaze.com (104.17.6.3:443)

Connecting to secure.backblaze.com (104.17.5.3:443)

wget: can't open '/wine/drive_c/install_backblaze.exe': File exists

Backblaze installer started, please go through the graphical setup in by logging onto the containers vnc server

````

**Comment by tom300z** [comment]
The logs look fine and the black screen on first start is normal (i just tested it). Pressing ALT+TAB should highlight the installer window. I have no idea how to send an alt+tab Keystroke from a mac, but you should be able to open a window select menu by pressing middle click (i think thats 3 finger tap on the touchpad)

![image](https://user-images.githubusercontent.com/10903523/146226699-9f3ca5f3-fd71-4382-8352-c8406c90219d.png)

**Comment by minovap** [comment]
Hi, thank you for your reply.

I tried on Windows 10 now with TightVNC and RealVNC Viewer, same issue. Middle mouse button does not show a menu either. I cleaned up the mounted /wine folder and tried again. On the initial run on a new container with blank folder I get the log below.

I connected with VNC as soon as the container booted and saw the popup for "configuring" wine.

Are there any way to config the bootup process so ALT+TAB is not needed?

`````
Starting the virtual display & vnc server

Backblaze not installed

Initializing the wine prefix

cp: can't stat '/wine//drive_c/Program Files/Backblaze/bzbui.exe.aside': No such file or directory


 --- x11vnc loop: 1 ---


_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

How are you gentlemen? All your base are belong to us. (Openbox received signal 11)

 --- x11vnc loop: waiting for: 26


Xlib:  extension "DPMS" missing on display ":0".


The VNC desktop is:      4ad999e3833a:0


0

wine: configuration in '/wine' has been updated.

Directory '//.local/share/mime/packages' does not exist!

wine: configuration in '/wine' has been updated.

Setting the wine computer name

The operation completed successfully

The operation completed successfully

The operation completed successfully

Downloading the Backblaze personal installer...

Connecting to www.backblaze.com (104.17.6.3:443)

Connecting to secure.backblaze.com (104.17.6.3:443)

saving to '/wine/drive_c/install_backblaze.exe'

install_backblaze.ex  48% |***************                 | 10.6M  0:00:01 ETA

install_backblaze.ex 100% |********************************| 22.0M  0:00:00 ETA

'/wine/drive_c/install_backblaze.exe' saved

Backblaze installer started, please go through the graphical setup in by logging onto the containers vnc server

````

**Comment by minovap** [comment]
I think I have narrowed it down to this:

````
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
````

Openbox is crashing. I am not familiar at all with openbox, but I assume that my issue with not seeing a window when pressing ALT+TAB is because of this.

**Comment by minovap** [comment]
I needed to tun the container as root 🥳

Thanks again for replying
